### ISSUE TITLE
Question about original paper

### ISSUE THREAD

**Issue by KingGugu** [HKUDS/AutoCF#1]
Thank you very much for your wonderful work and open source code. But I can't download the original file of the paper on all platforms. Can you give the download link of the paper or upload the paper to the code repository?

Thank you.

**Comment by akaxlh** [comment]
Thank you for your interest in our new work!
The camera-ready version is still under processing by WWW'23, and we have just submitted the paper to arxiv today. It will be available in several days, and we will update the link in this repo.
