### ISSUE TITLE
为什么YELP数据集中的user只有42712

### ISSUE THREAD

**Issue by primising** [HKUDS/AutoCF#10]

**Comment by akaxlh** [comment]
你好，这个数据集经过了一些筛选，主要是筛出了一段时间内的交互记录

**Comment by primising** [comment]
> 你好，这个数据集经过了一些筛选，主要是筛出了一段时间内的交互记录

请教一下encoderAdj是去除了种子节点的子图, decoderAdj是数据增强后的图，我这样理解对吗？一般的掩码都是掩码后放进模型训练，这个是生成了两个子图分别去训练，这样有什么好处？

**Comment by akaxlh** [comment]
你好，encoderAdj是去除了被选中子图中所有边的图，种子节点只是一开始选中的子图中心节点，中心节点周围两跳的所有边都被删除了。decoderAdj是在encoderAdj的基础上，随机采样一些边的结果。本质上是对encoderAdj进行reconstruction，但是这种mask方式会使encoderAdj中出现完全孤立的节点，因此进行sampling graph self-attention，使孤立点的embedding也可以进行信息传播更新。

**Comment by primising** [comment]
> 你好，encoderAdj是去除了被选中子图中所有边的图，种子节点只是一开始选中的子图中心节点，中心节点周围两跳的所有边都被删除了。decoderAdj是在encoderAdj的基础上，随机采样一些边的结果。本质上是对encoderAdj进行reconstruction，但是这种mask方式会使encoderAdj中出现完全孤立的节点，因此进行sampling graph self-attention，使孤立点的embedding也可以进行信息传播更新。

很抱歉再麻烦你，我在代码里没有找到损失函数INFOM和RECON

**Comment by akaxlh** [comment]
你好，这两个损失分别在Main.py的93行和85行
