### ISSUE TITLE
关于源码

### ISSUE THREAD

**Issue by ZzYUuuu** [HKUDS/AutoCF#11]
请问为什么我在源码中无法寻找到关于计算Lrecon损失的部分？

**Comment by akaxlh** [comment]
你好，reconstruction loss和推荐主任务loss的目的都是预测正例边，因此在实现的时候没有特意对masked edges进行采样、重建，从而简化模型。

**Comment by ZzYUuuu** [comment]
好的，谢谢您

**Comment by ZzYUuuu** [comment]
好的，谢谢您的回答
