### ISSUE TITLE
代码里没有用到验证集？

### ISSUE THREAD

**Issue by primising** [HKUDS/AutoCF#13]
这种测试结果是规范的吗

**Comment by akaxlh** [comment]
你好，这个工作用到了验证集。DataHandler.py里21行的tstMat.pkl替换成valMat.pkl即为使用验证集进行调参。这份代码没有使用early stop，而是固定epoch number，所以在训练模型得到最终测试结果的过程中不需要使用验证集。

**Comment by primising** [comment]
> 你好，这个工作用到了验证集。DataHandler.py里21行的tstMat.pkl替换成valMat.pkl即为使用验证集进行调参。这份代码没有使用early stop，而是固定epoch number，所以在训练模型得到最终测试结果的过程中不需要使用验证集。
那不是相当于对着测试集调参了吗，我不太理解“这份代码没有使用early stop，而是固定epoch number，所以在训练模型得到最终测试结果的过程中不需要使用验证集。”

**Comment by akaxlh** [comment]
你好，使用验证集调参，调完参数以后换测试集测试。
early stop技术相当于在训练过程中实时调整epoch数量这一超参，因此本身需要使用验证集。除了这种实时调参的情况，其他超参数在验证集上确定以后再跑测试即可。

**Comment by primising** [comment]
> 你好，使用验证集调参，调完参数以后换测试集测试。 early stop技术相当于在训练过程中实时调整epoch数量这一超参，因此本身需要使用验证集。除了这种实时调参的情况，其他超参数在验证集上确定以后再跑测试即可。

了解了 感谢你的回复

**Comment by akaxlh** [comment]
不客气，感谢您的讨论
