### ISSUE TITLE
关于对比模型的设置问题

### ISSUE THREAD

**Issue by primising** [HKUDS/AutoCF#14]
我将原文代码`usrEmbeds, itmEmbeds = self.model(encoderAdj, decoderAdj)`改成`usrEmbeds, itmEmbeds = self.model(self.handler.torchBiAdj）`来模拟lightgcn模型，其他地方不动，最后的模型结果recall@20来到了0.079远高于原文中提到的0.0761

**Comment by akaxlh** [comment]
您好，您描述的这个版本和LightGCN存在一些差异，单独去除AutoCF的data augmentation部分并不会disable AutoCF的附加loss，比如L_ssl的前三项、L_infoM。您描述的这个模型更接近于一个改版的SGL。可以看到，0.079的效果也不如我们跑出的SGL效果0.0803。
若您发现可以进一步提升某几个baseline的效果，欢迎讨论。

**Comment by primising** [comment]
> 您好，您描述的这个版本和LightGCN存在一些差异，单独去除AutoCF的data augmentation部分并不会disable AutoCF的附加loss，比如L_ssl的前三项、L_infoM。您描述的这个模型更接近于一个改版的SGL。可以看到，0.079的效果也不如我们跑出的SGL效果0.0803。 若您发现可以进一步提升某几个baseline的效果，欢迎讨论。
我发现需要代码中bprLoss + contrastLoss结合使用，去除contrastLoss后，loss会迅速向负无穷方向去。若想直接模拟LightGCN是不是把这部分的LOSS改成BPRLOSS才行。

**Comment by primising** [comment]
我发现需要代码中bprLoss + contrastLoss结合使用，去除contrastLoss后，loss会迅速向负无穷方向去。若想直接模拟LightGCN是不是把这部分的LOSS改成BPRLOSS才行。

**Comment by akaxlh** [comment]
是的，只有代码里的“bprLoss"相当于没有负样例了，模型直接给所有交互大分数训练loss就好了。代码里的"bprLoss"实际不是bpr，早期版本起了名字以后，迭代过程中没有改。

**Comment by akajinchen** [comment]
> 是的，只有代码里的“bprLoss"相当于没有负样例了，模型直接给所有交互大分数训练loss就好了。代码里的"bprLoss"实际不是bpr，早期版本起了名字以后，迭代过程中没有改。

你好 源码中的bprloss可以看成是alignment loss和重构loss吗
