### ISSUE TITLE
关于代码中计算注意力的部分，恳请解惑

### ISSUE THREAD

**Issue by akajinchen** [HKUDS/AutoCF#16]
代码中计算注意力得分是“att = t.einsum('ehd, ehd -> eh', qEmbeds, kEmbeds)”
为什么不是“att = t.einsum('ihd, jhd -> ijh', qEmbeds, kEmbeds)”呢

**Comment by akaxlh** [comment]
你好，感谢提问。你描述的是sequence transformer里那种任意两两关系，节点之间两两关系对图模型来说太大了。这里的Graph self-attention是在选取了部分边的基础上，只算这部分边的attention，相当于对O(N*N)的任意两两关系做了一个采样。具体来说，这里采样的关系集合包括mask后剩下的所有边，以及随机采样的一些边。
