### ISSUE TITLE
关于数据集的问题

### ISSUE THREAD

**Issue by akajinchen** [HKUDS/AutoCF#17]
你好，感谢你出色的论文和开源的代码，但是我有一个关于数据集的问题。文章中数据集表格的交互次数指的是整个数据集中的交互次数还是分割后训练集的交互次数呢？我看到源码的Amazon trnmat的nnz就是966680了，恳请解答。

**Comment by akaxlh** [comment]
您好，那论文里展示的Amazon交互次数应该是训练集的。这里写整个数据集更合适一些，感谢您指出这一问题。

**Comment by akajinchen** [comment]
> 您好，那论文里展示的Amazon交互次数应该是训练集的。这里写整个数据集更合适一些，感谢您指出这一问题。

**Comment by akajinchen** [comment]
> 您好，那论文里展示的Amazon交互次数应该是训练集的。这里写整个数据集更合适一些，感谢您指出这一问题。

感谢你的回答，解决了我的疑惑
