### ISSUE TITLE
代码报错问题

### ISSUE THREAD

**Issue by kkkkkobe** [HKUDS/AutoCF#18]
您好，有个问题需要请教一下
torch._C._cuda_init() 这句代码报错
报错信息：
RuntimeError: No CUDA GPUs are available

**Comment by akaxlh** [comment]
您好，感谢您的问题。可能是因为params.py里我把默认gpu设置成'2'了，您改过来试一下。

**Comment by kkkkkobe** [comment]
谢谢您的答复。
