### ISSUE TITLE
关于对比实验的结果

### ISSUE THREAD

**Issue by mxx910** [HKUDS/AutoCF#2]
你好,请问AutoCF论文中对比模型的实验结果是通过贵组的[SSLRec](https://github.com/HKUDS/SSLRec)框架实现的吗

**Comment by akaxlh** [comment]
你好，我用的和SSLRec的实现基本上是一样的，在统一框架时有些小的改动，最终效果应该差别不大。

**Comment by mxx910** [comment]
好的 谢谢
