### ISSUE TITLE
细节疑问

### ISSUE THREAD

**Issue by TangJiakai** [HKUDS/AutoCF#4]
您好，这份工作比较复杂，但效果提升很大。有一些细节我有些疑问：
1. 为什么解码时是从全局U并I的pair set中随机取并对他们连边，然后再最小化他们的相似度，不理解这种随机建边的方式并优化他们的亲密度为什么是合理的。以及公式(9)的\varepsilon 是不是少了个\bar?
2. 为什么encoder和decoder结构需要不一样，encoder也用自注意力加权的方式有什么缺陷吗？

**Comment by akaxlh** [comment]
您好，感谢关注，关于您提到的两个疑问：
1. 这个做法其实是一种efficient transformer，出发点是首先按照transformer的思路去学习任意两点的关系，但推荐数据集结点太多，O(N^2)的关系数量太大，因此稀疏随机采样某些node pair进行两两关系学习。这里需要采用transformer是因为，我们前面采用的mask方法会完整地mask一个子图内的所有边，导致很多节点变成孤立点，GCN就没法学习他们的特征。为了对这些节点进行信息传播和表征学习，必须采用一种全局的建模方式（相对于依赖masked graph的GCN）。

- 公式9想表达的是对masked edge的重建，和efficient transformer的采样无关。不过公式9和推荐的训练目标结合起来，其实我们并没有特定对mased edge进行重建，而是对所有u-i边进行重建训练。顺便一提，我们正在完成的工作中发现基于低秩的efficient transformer效果同样不错。

3. 就像你前面提到的，直观来说这种采样的efficient transformer所利用的node pair关系不一定准确，因此我们在encoder部分采用直接利用图结构的lightgcn先卷一遍，让节点embedding获得更可靠的图结构信息，这样也能让transformer利用的节点embedding更可靠，从而在self-attention计算里面更准确。

**Comment by TangJiakai** [comment]
感谢您的耐心回复，但
1. 抱歉，我仍然无法理解，我第一个疑问在于随机选边，这大概率是潜在真实label=0的交互，而文中其实直接把这个随机边视作label=1的交互去做，为什么说他会对模型有正向作用呢？如果您是部分恢复之前随机mask的边，那我觉得没问题，但文中应该不是这个意思
2. 是的，直接这样lightgcn encoder得到的不一定准确，那为什么不直接在encoder使用transformer结构去做呢？这样同样也可以捕捉到图结构，而且也比目前普通卷积更准确

**Comment by akaxlh** [comment]
你好，感谢你的回复。
1. 推荐数据中用户只会接受很少的曝光，导致大部分边的label是0，但这不意味着这些节点之间没有相似关系。这里应用self-attention的目的是通过学习所有可能的node-wise relations，去挖掘潜在的、未观测到的联系。在我们的模型中，这一点的必要性在于，经过了对一些subgraph的完全mask，图结构至少在局部遭到了严重的破坏，完全依赖图结构的GCN无法对这样的破坏部分进行信息传播。
2. 您说的这种方法是可以的，这里模型设计主要是考虑到了LightGCN高效、效果好、易于训练的特点。

**Comment by TangJiakai** [comment]
谢谢您的回答！
