### ISSUE TITLE
嵌入维度的问题

### ISSUE THREAD

**Issue by BlueGhostZ** [HKUDS/AutoCF#5]
作者您好，感谢您精彩的工作并将其开源。在附录的图11给出了Yelp和Gowalla数据集上不同嵌入大小的性能，可以发现AutoCF在嵌入大小为30以后就没有进一步的性能提升了，而在4.1.3中所有的默认嵌入大小设置为32，这对于其他基线模型（例如LightGCN、SGL）是否公平？因为广泛的设置是64，并且许多工作已经指出这些工作在更大的嵌入设置（例如128和256）下可以取得更好的性能表现。
此外，作者是否有考虑过和SimGCL/XSimGCL进行对比呢？在先前的研究中，SimGCL被证实是一种简单且有效的图对比推荐方法，并且可以取得比SGL、NCL等方法更好的性能。
感谢阅读，期待您的回复。

**Comment by akaxlh** [comment]
你好，感谢您对我们工作的关注。文章发表后我尝试过SimGCL的效果，使用原作代码经过调参得到的效果如下：Gowalla 0.2352，0.1556；Yelp 0.0842，0.0424；Amazon 0.1012，0.0682。SimGCL的效果确实优于一些其他的baseline，与之相比我们仍然有一定的优势。
您关于embedding size的观察非常细致深刻。按照之前工作的经验来说，AutoCF的效果确实应当继续随embedding size增长而增长。我猜测可能有两种原因导致了这一异常结果，首先是我们使用的数据集监督信号不足，在大embedding size上容易过拟合。其次是AutoCF模型本身在大embedding size上可能更容易过拟合，而我们测试d=64时并没有调整其他超参数，导致模型出现过拟合、效果没有进一步增长。

**Comment by BlueGhostZ** [comment]
非常感谢您的回复，期待您更多新的工作。

**Comment by akaxlh** [comment]
感谢回复，同样期待您的成果。

**Comment by LarFii** [comment]
> 作者您好，感谢您精彩的工作并将其开源。在附录的图11给出了Yelp和Gowalla数据集上不同嵌入大小的性能，可以发现AutoCF在嵌入大小为30以后就没有进一步的性能提升了，而在4.1.3中所有的默认嵌入大小设置为32，这对于其他基线模型（例如LightGCN、SGL）是否公平？因为广泛的设置是64，并且许多工作已经指出这些工作在更大的嵌入设置（例如128和256）下可以取得更好的性能表现。 此外，作者是否有考虑过和SimGCL/XSimGCL进行对比呢？在先前的研究中，SimGCL被证实是一种简单且有效的图对比推荐方法，并且可以取得比SGL、NCL等方法更好的性能。 感谢阅读，期待您的回复。

您好，最近在研究嵌入大小对模型性能的影响，能举例一些提到有关嵌入大小的论文吗，不甚感激。

**Comment by BlueGhostZ** [comment]
> > 作者您好，感谢您精彩的工作并将其开源。在附录的图11给出了Yelp和Gowalla数据集上不同嵌入大小的性能，可以发现AutoCF在嵌入大小为30以后就没有进一步的性能提升了，而在4.1.3中所有的默认嵌入大小设置为32，这对于其他基线模型（例如LightGCN、SGL）是否公平？因为广泛的设置是64，并且许多工作已经指出这些工作在更大的嵌入设置（例如128和256）下可以取得更好的性能表现。 此外，作者是否有考虑过和SimGCL/XSimGCL进行对比呢？在先前的研究中，SimGCL被证实是一种简单且有效的图对比推荐方法，并且可以取得比SGL、NCL等方法更好的性能。 感谢阅读，期待您的回复。
> 
> 您好，最近在研究嵌入大小对模型性能的影响，能举例一些提到有关嵌入大小的论文吗，不甚感激。

例如发表于CIKM‘21的How Powerful is Graph Convolution for Recommendation?论文给出了LightGCN在不同维度下的性能表现

**Comment by LarFii** [comment]
> > > 作者您好，感谢您精彩的工作并将其开源。在附录的图11给出了Yelp和Gowalla数据集上不同嵌入大小的性能，可以发现AutoCF在嵌入大小为30以后就没有进一步的性能提升了，而在4.1.3中所有的默认嵌入大小设置为32，这对于其他基线模型（例如LightGCN、SGL）是否公平？因为广泛的设置是64，并且许多工作已经指出这些工作在更大的嵌入设置（例如128和256）下可以取得更好的性能表现。 此外，作者是否有考虑过和SimGCL/XSimGCL进行对比呢？在先前的研究中，SimGCL被证实是一种简单且有效的图对比推荐方法，并且可以取得比SGL、NCL等方法更好的性能。 感谢阅读，期待您的回复。
> > 
> > 
> > 您好，最近在研究嵌入大小对模型性能的影响，能举例一些提到有关嵌入大小的论文吗，不甚感激。
> 
> 例如发表于CIKM‘21的How Powerful is Graph Convolution for Recommendation?论文给出了LightGCN在不同维度下的性能表现
非常感谢！
