### ISSUE TITLE
关于局部图构造的过程

### ISSUE THREAD

**Issue by BlueGhostZ** [HKUDS/AutoCF#6]
作者您好。我发现在开源代码的methods/Model.py的81~97行对应了论文中3.1.2的内容。论文里的描述是计算衡量中心节点的k-阶邻居的分数s，在论文和代码里k=2，根据代码我发现作者是通过以下方式得到中心节点的2阶邻居的初始嵌入和：

![$N(JA7Q~B8FXJ{PH%CATJW](https://github.com/HKUDS/AutoCF/assets/71833100/6b7ab1d1-12a2-43fa-a35f-cbeb135cf7be)
根据这一过程我自己做了一些简单的推导，如下图：
![8) {$5` EDHT 9UONRSBXLT](https://github.com/HKUDS/AutoCF/assets/71833100/5e286e65-4e16-4f77-ad37-df270bf89646)
可以看到，右侧的E0、E1和E2分别是嵌入表，E1通过E0得到，而E2通过E1和E0得到。以E1的第一行为例，因为用户A1交互过L1和L2，所以A1的一阶邻居节点的嵌入之和为0.5+0.6=1.1，而在计算二阶交互时，再一次做信息聚合，E2第一行对应的值变为1.1+0.3+0.6-1.1，值为0.9，随后根据代码order * embeds减掉3次E0，即0.9-0.3=0.6。但根据实际情况，A1的二阶邻居是A2和A3，其二阶邻居的嵌入和应该是0.2+0.3=0.5，这和计算过程不符合。
我对此存在一些困惑，非常期待您的回复。

**Comment by akaxlh** [comment]
您好，感谢您对我们工作细致的研究。

您的E1计算过程完全没有问题，计算E2时，A1的embedding和您计算的一样，首先是0.3+0.6+1.1-1.1=0.9，然后应该是剪掉2次A1的0阶embedding，因为A1的度是2，结果变成0.9-0.2=0.7，会发现实际上A2和A3的和应该是0.2+0.3=0.5，我们的计算结果多了0.2，这是因为A2被A1的一阶邻居L1和L2一共访问了两次，因此在我们的计算中A2的embedding0.2被多加了一次。

当时设计这个算法时，应该是觉得这样做考虑了邻居节点连接到中心节点path的数量差别，也是比较合理的。只要消除中心节点自己的embedding，我们的相似度分数就不会包括中心节点自己和自己相似度的分量，就能更好地反映中心和context之间的关系。

如果要严格计算k跳内每个节点embedding的和，可以利用无self-loop的矩阵A，进行如下计算(A * A != 0) * E，这里 * 代表矩阵乘法，!=代表elementwise不等于操作。这里!=0可以消除path数量的差别。但这样做就必须先计算A^2，会带来较大的空间开销（存储A^2），或时间开销（分batch对行操作）。

**Comment by BlueGhostZ** [comment]
感谢您的回复。我还有一个问题是论文中提到了掩码图的重构过程（Eq. 9），但我在开源代码里好像没有找到公式9的对应的计算过程。

**Comment by HKUDS** [comment]
您好，由于也做了推荐的主任务，两个过程事实上重合了，就没有单独训练对掩码进行重构，论文为了完整性提及了重构过程。

**Comment by akaxlh** [comment]
您好，事实上重构过程和推荐主任务重合了，就没有单独进行掩码图重构。论文为了完整性提及了重构过程。

**Comment by BlueGhostZ** [comment]
非常感谢您的回复。

**Comment by rsrcoderplay** [comment]
你好，这里的A矩阵不加入自连接可以吗？

**Comment by akaxlh** [comment]
你好，是可以的，我们这部分的具体计算过程也是在去除自连接，如果本身邻接矩阵不带自链接，应该要修改一下LocalGraph部分的代码

**Comment by rsrcoderplay** [comment]
> 

谢谢大佬的回复。

**Comment by BEIDABODAO** [comment]
> 您好，感谢您对我们工作细致的研究。
> 
> 您的E1计算过程完全没有问题，计算E2时，A1的embedding和您计算的一样，首先是0.3+0.6+1.1-1.1=0.9，然后应该是剪掉2次A1的0阶embedding，因为A1的度是2，结果变成0.9-0.2=0.7，会发现实际上A2和A3的和应该是0.2+0.3=0.5，我们的计算结果多了0.2，这是因为A2被A1的一阶邻居L1和L2一共访问了两次，因此在我们的计算中A2的embedding0.2被多加了一次。
> 
> 当时设计这个算法时，应该是觉得这样做考虑了邻居节点连接到中心节点path的数量差别，也是比较合理的。只要消除中心节点自己的embedding，我们的相似度分数就不会包括中心节点自己和自己相似度的分量，就能更好地反映中心和context之间的关系。
> 
> 如果要严格计算k跳内每个节点embedding的和，可以利用无self-loop的矩阵A，进行如下计算(A * A != 0) * E，这里 * 代表矩阵乘法，!=代表elementwise不等于操作。这里!=0可以消除path数量的差别。但这样做就必须先计算A^2，会带来较大的空间开销（存储A^2），或时间开销（分batch对行操作）。

您好，您提到减去2次A1的0阶embedding，是因为A1的一阶邻居（度）有2个，但是在代码中计算度的结果为3，这是为什么呢

**Comment by akaxlh** [comment]
您好，是否还有self-loop的影响？

**Comment by ZzYUuuu** [comment]
作者您好，关于二阶邻居的数量，如上图的A1，容易看出是有两个结点的，但是根据源码：
scdNum = (t.spmm(allOneAdj, fstNum) - fstNum) - order
我的计算得出却是 scdNum_A1 =( (2*1+3*1) -2)-2=1,所以为什么考虑再减去order呢？

**Comment by akaxlh** [comment]
> 作者您好，关于二阶邻居的数量，如上图的A1，容易看出是有两个结点的，但是根据源码： scdNum = (t.spmm(allOneAdj, fstNum) - fstNum) - order 我的计算得出却是 scdNum_A1 =( (2_1+3_1) -2)-2=1,所以为什么考虑再减去order呢？

您好，-fstNum是为了消除自连接，-order是为了消除自己本身在一阶邻居的fstNum中重复的次数，这里代码计算结果应该是3，重复了一次L1 L2的共同邻居A2

**Comment by akajinchen** [comment]
> 作者您好。我发现在开源代码的methods/Model.py的81~97行对应了论文中3.1.2的内容。论文里的描述是计算衡量中心节点的k-阶邻居的分数s，在论文和代码里k=2，根据代码我发现作者是通过以下方式得到中心节点的2阶邻居的初始嵌入和：
> 
> ![$N(JA7Q~B8FXJ{PH%CATJW](https://private-user-images.githubusercontent.com/71833100/240095588-6b7ab1d1-12a2-43fa-a35f-cbeb135cf7be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1MzQ3MjMsIm5iZiI6MTcwMTUzNDQyMywicGF0aCI6Ii83MTgzMzEwMC8yNDAwOTU1ODgtNmI3YWIxZDEtMTJhMi00M2ZhLWEzNWYtY2JlYjEzNWNmN2JlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAyVDE2MjcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwODk3ODMxNjc1MmMxY2VhMmJmZjMwN2E1NjQzOTU5NGEwOTM3MDMzMmY1ZDg2YzM5YzRmMWU3ZWE4ZTZlNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ibFO9TjXIvOcYNnceLaRISwOM2Gz5OQ7mjkD1f4BtzM) 根据这一过程我自己做了一些简单的推导，如下图： ![8) {$5` EDHT 9UONRSBXLT](https://private-user-images.githubusercontent.com/71833100/240095713-5e286e65-4e16-4f77-ad37-df270bf89646.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1MzQ3MjMsIm5iZiI6MTcwMTUzNDQyMywicGF0aCI6Ii83MTgzMzEwMC8yNDAwOTU3MTMtNWUyODZlNjUtNGUxNi00Zjc3LWFkMzctZGYyNzBiZjg5NjQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAyVDE2MjcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxM2FhOWUwZGY5ZWYxMDA5OWQ1NmE1NDIyYjhjZDczYTk5NDFkMmM4ZmY5NGFlOTY0ZDZkMjY2MDBmNTAzNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DxD3t6hxsN52YD2Y01BUHenQY19w_E95xyLZ9RHBNw4) 可以看到，右侧的E0、E1和E2分别是嵌入表，E1通过E0得到，而E2通过E1和E0得到。以E1的第一行为例，因为用户A1交互过L1和L2，所以A1的一阶邻居节点的嵌入之和为0.5+0.6=1.1，而在计算二阶交互时，再一次做信息聚合，E2第一行对应的值变为1.1+0.3+0.6-1.1，值为0.9，随后根据代码order * embeds减掉3次E0，即0.9-0.3=0.6。但根据实际情况，A1的二阶邻居是A2和A3，其二阶邻居的嵌入和应该是0.2+0.3=0.5，这和计算过程不符合。 我对此存在一些困惑，非常期待您的回复。

你好 这里的图是用什么画的呢
