### ISSUE TITLE
import setproctitle

### ISSUE THREAD

**Issue by a951160430** [HKUDS/AutoCF#7]
“ModuleNotFoundError: No module named 'setproctitle'”

您好，怎么安装setproctitle这个包呀？

**Comment by akaxlh** [comment]
您好，这个包是为了在多人使用服务器时标识自己的进程，可以不用。安装命令：
```
pip install setproctitle
```

**Comment by a951160430** [comment]
谢谢您的回复，这两个问题已经解决了，我的代码水平一般😂，还在看代码，请问在跑amazon数据集时显存不够怎么解决的，您遇到过这个问题吗？

**Comment by akaxlh** [comment]
你好，可以考虑用更小的embedding size、更少的gnn layer、更小的数据集，或者换更大显存的显卡

**Comment by a951160430** [comment]
夏哥，我在您的另一篇文章LightGCL的代码中，遇到点问题，方便回答一下吗。就是在LightGCL的parser1中，data的default='yelp'，，但我修改yelp，改为gowalla和ml10m数据集，还是在跑yelp数据集，请问这是为什么？怎么修改为在其它数据集上跑？
