### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by hunaghuohui** [HKUDS/AutoCF#9]
抱歉，temNum = maskNodes.shape[0]
		temRows = maskNodes[t.randint(temNum, size=[adj._values().shape[0]]).cuda()]
		temCols = maskNodes[t.randint(temNum, size=[adj._values().shape[0]]).cuda()]

		newRows = t.concat([temRows, temCols, t.arange(args.user+args.item).cuda(), rows])
		newCols = t.concat([temCols, temRows, t.arange(args.user+args.item).cuda(), cols])

		# filter duplicated
		hashVal = newRows * (args.user + args.item) + newCols
		hashVal = t.unique(hashVal)
		newCols = hashVal % (args.user + args.item)
		newRows = ((hashVal - newCols) / (args.user + args.item)).long()
生成解码图过程这段代码我无法理解，你能为我解释一下吗，感谢

**Comment by akaxlh** [comment]
你好，同样前缀的Rows和Cols记录的是同一组边的节点信息，具体来说
- temRows和temCols是从和被mask的边相关的所有节点（maskNodes）中，随机采样一些边进行关系建模。因为这些节点的相关结构被mask了，所以希望对他们之间的任意关系进行学习，但这种平方级别的关系数量太多，所以进行采样，这里默认采样和原始图相同数量的边。
- newRows和newCols是将tem边双向重复，再加上self-loop以后的edge list
- filter duplicated部分，由于是list of pairs，不能直接用t.unique函数进行去重，所以先用哈希算法把pair映射成一个数字，再进行去重

**Comment by hunaghuohui** [comment]
感谢你的回答
